# Configuración de headers HTTP para seguridad
# Este archivo puede usarse con Netlify o adaptarse para otros servicios como Vercel, Cloudflare Pages, etc.

[[headers]]
  for = "/*"
  [headers.values]
    # Seguridad básica
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    
    # Configuración HSTS (HTTP Strict Transport Security)
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
    
    # Content Security Policy (CSP)
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' https://calendly.com https://assets.calendly.com https://www.google-analytics.com https://www.googletagmanager.com; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; img-src 'self' data: https:; font-src 'self' https://fonts.gstatic.com; connect-src 'self' https://api.tecniservice.cl; frame-src https://calendly.com https://assets.calendly.com; object-src 'none'; base-uri 'self';"
    
    # Cross-Origin-Embedder-Policy (COEP)
    Cross-Origin-Embedder-Policy = "require-corp"
    
    # Cross-Origin-Opener-Policy (COOP)
    Cross-Origin-Opener-Policy = "same-origin"
    
    # Cross-Origin-Resource-Policy (CORP)
    Cross-Origin-Resource-Policy = "same-site"
    
    # Permissions Policy
    Permissions-Policy = "geolocation=(self), camera=(), microphone=(), payment=(), xr-spatial-tracking=()"
    
    # Cache-Control para archivos estáticos (excluye HTML)
    Cache-Control = "public, max-age=0, must-revalidate"

# Headers específicos para recursos estáticos (CSS, JS, imágenes)
[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.webp"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.png"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.svg"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.woff2"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"